import { type NextPage } from "next";
import Head from "next/head";

import { Heading, UrlForm, UrlList } from "~/components";

import styles from "./index.module.scss";
import { type Metadata, type Url } from "@prisma/client";
import { api } from "~/utils/api";

export type UrlWithMetadata = Url & {
	metadata: Metadata | null;
};

export type LocalUrl = Pick<Url, "code" | "destinationUrl">;

const Home: NextPage = () => {
	// TODO: Get URLs by user ID
	const { data: urls } = api.url.getAll.useQuery();

	return (
		<>
			<Head>
				<title>teeny.fun</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link
					rel="icon"
					href="/favicon.png"
					type="image/png"
				/>
			</Head>
			<main className={styles.main}>
				<header className={styles.header}>
					<Heading tag="h1">
						<Heading.Span
							text="teenify"
							color="yellow"
							index={0}
						/>
						<Heading.Span
							text="URLs with"
							color="white"
							index={1}
						/>
						<Heading.Span
							text="emojis"
							color="yellow"
							index={2}
						/>
					</Heading>
				</header>
				<section className={styles.container}>
					<UrlForm />
					{urls && <UrlList urls={urls} />}
				</section>
			</main>
		</>
	);
};

export default Home;
